Text = {}
Text.BASE_CAPTURED = "We have captured %s."
Text.BASE_LOST = "We have lost %s."
Text.BASE_SAFE = "Well done. %s is now safe. Make sure to keep it that way."
Text.BASE_CAPTURE_IMMINENT =
"Base %s is about to be captured. Kill the enemies inside the capture zone or we will lose the base. You have %s seconds."
Text.BASE_CAPTURE_IN_PROGRESS = "We're starting the capture of the base. Give us %s seconds."
Text.GARRISON_LEAVING_PERIMETER =
"You're leaving the base perimeter. Return to the perimeter immediately or you will be destroyed. You have %s seconds."
Text.GARRISON_RETURNING_PERIMETER =
"Glad you decided to return. Make sure you don't leave the base perimeter soldier."
Text.NOT_CLOSE_ENOUGH_LOGISTICS = "Unable, we need to be close to a logistics center."
Text.LAND_FIRST = "Unable, you need to land first."
Text.CARGO_ON_BOARD_ALREADY = "Unable, you already have cargo on-board."
Text.NEED_LOGISTICS_CENTER = "Unable, you need to be close to a logistics center."
Text.NO_PERSONNEL_ON_BOARD = "Unable, no personnel on-board."
Text.CANNOT_SPAWN = "Unable, make sure the location is not obstructed."
Text.NO_SUPPLIES_NEARBY = "Unable, no supplies nearby (%sm)."
Text.NOT_ENOUGH_SUPPLIES_ON_CRATE =
"Unable, there aren't enough supplies nearby (available: %s | required: %s)."
Text.NO_SUPPLIES_LEFT_CRATE = "No supplies left on the crates."
Text.SUPPLIES_LEFT_CRATE = "Still %s supplies left on the crate(s)."
Text.CRATE_ALREADY_SPAWNED = "Unable, there is already a crate in front of you."
Text.NOT_ENOUGH_SUPPLIES_FACTION = "Unable, we don't have enough supplies to comply with your request."
Text.NO_CARGO_NEARBY = "Unable, no cargo nearby."
Text.NO_PERSONNEL_NEARBY = "Unable, no personnel nearby."
Text.NO_CARGO_ON_BOARD = "No cargo on-board."
Text.PERSONNEL_ON_BOARD_ALREADY = "Unable, you already have personnel on-board."
Text.NOT_ENOUGH_SEATS = "Unable, not enough seats available."
Text.NO_FRIENDLY_PILOT_FOUND = "Unable, could not find any friendly pilot nearby (%sm)."
Text.PILOT_RESCUED = "We've rescued %s."
Text.PILOT_RETURNED = "We've have returned %s to base."